apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbt-env
  namespace: streaming-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dbt-env
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: kv/projects/streaming-demo/dbt
