apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbt-env
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dbt-env
    creationPolicy: Owner
  data:
    - secretKey: DBT_PROFILES_DIR
      remoteRef:
        key: streaming-demo
        property: dbt_profiles_dir
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: streaming-demo
        property: postgres_host
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: streaming-demo
        property: postgres_port
    - secretKey: POSTGRES_USER
      remoteRef:
        key: streaming-demo
        property: postgres_user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: streaming-demo
        property: postgres_password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: streaming-demo
        property: postgres_db
    - secretKey: POSTGRES_SCHEMA
      remoteRef:
        key: streaming-demo
        property: postgres_schema
