apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dbt-env
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dbt-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kv/projects/streaming-demo/dbt
