apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-dbt-env
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: airflow-dbt-env
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: kv/airflow-dbt