apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unitycatalog-api
  namespace: data-platform
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: uc-api.tpomaville.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unity-catalog-unitycatalog-server
            port:
              number: 8080